#!/bin/bash 
#PBS -k o 
#PBS -l nodes=2:ppn=32:dc2
#PBS -l walltime=00:15:00
#PBS -N JobName 
#PBS -q debug_cpu

module load ccm

export OMP_NUM_THREADS=2
##ccmrun mpiexec -np 2 --map-by node -machinefile $PBS_NODEFILE hostname
ccmrun mpiexec --map-by ppr:16:node  -machinefile $PBS_NODEFILE /N/u/vafandal/BigRed2/cppNTT/search -ram 4 -threads 2 -n 5 -dir /N/dc2/scratch/vafandal/n2t1r12/

